---
title: "main_A1"
author: "Xiaotong Li"
date: "11/19/2019"
output: html_document
---


### Step 1 Load Data and Train-test Split
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
data <- read.csv("../data/ml-latest-small/ratings.csv")
set.seed(0)
test_idx <- sample(1:nrow(data), round(nrow(data)/5, 0))
train_idx <- setdiff(1:nrow(data), test_idx)
data_train <- data[train_idx,]
data_test <- data[test_idx,]
```

## Parameter tuning results: f=10, lambda= 0.1


```{r, eval= FALSE}
source("../lib/Matrix_Factorization.r")
result <- gradesc(f = 10, lambda = 0.1,lrate = 0.01, max.iter = 240, stopping.deriv = 0.01,
                   data = data, train = data_train, test = data_test)

save(result, file = "../output/mat_fac.RData")
```


# Post-processing by P3

```{r}
source("../lib/P3.r")
load("../output/mat_fac.RData")

rating = t(result$p) %*% result$q
X = X_mat(result$q)
n = nrow(X)
lamb = 0.5
I = diag(n)
```

```{r}
# SVD_KRR
svd_krr_pred_rating <- K(X,X) %*% solve((K(X,X)+lamb*I)) %*% t(rating)
# (mxm)

#define a function to extract the corresponding predictedrating for the test set.
extract_pred_rating <- function(test_set, pred){
  pred_rating <- pred[as.character(test_set[2]), as.character(test_set[1])]
  return(pred_rating)
}
#extract predicted rating
pred_test_rating <- apply(data_test, 1, extract_pred_rating, svd_krr_pred_rating)
# number of rows of data test 

save(svd_krr_pred_rating, file = "../output/A1_P3.RData")
```


# Evaluation

```{r}
library(ggplot2)

RMSE <- data.frame(epochs = seq(10, 240, 10), Training_MSE = result$train_RMSE, Test_MSE = result$test_RMSE) %>% gather(key = train_or_test, value = RMSE, -epochs)

RMSE %>% ggplot(aes(x = epochs, y = RMSE,col = train_or_test)) + geom_point() + scale_x_discrete(limits = seq(10, 240, 10)) + xlim(c(0, 240))
```


```{r}
RMSE_mat <- function(T, Y){
 E    = T-Y;
 SQE  = E^2
 MSE  = mean(SQE)
 RMSE = sqrt(MSE)
 return(RMSE)}

RMSE_mat(T = rating, Y =t(svd_krr_pred_rating) )
```

